[build]
builder = "NIXPACKS"
buildCommand = "cd backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && gunicorn server:app --bind 0.0.0.0:$PORT --timeout 300 --workers 2 --log-level info"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

